services:
  forward-fil-bot:
    build: .
    environment:
      API_ID: $API_ID
      API_HASH: $API_HASH
      BOT_TOKEN: $BOT_TOKEN	
      MONGODB_URI: $MONGODB_URI
      LOG_CHANNEL: $LOG_CHANNEL
      OWNER_ID: $OWNER_ID

    resources:
      cpu: 1000m
      memory: 3Gi